### ISSUE TITLE
one way to do it!

### ISSUE THREAD

**Issue by soumith** [dfm/github-repo-crawler#1]
For what it's worth, this is what I use, it's super simple. It uses the command-line utility "hub" http://hub.github.com/

``` bash
#!/bin/bash
ghusername="soumith"
git hub network 2>/dev/null|grep '"$ghusername" -> ' |cut -f4 -d'"'|xargs -I {} bash -c 'mkdir -p {} && cd {} && git hub mirror --goblet {}/* && sleep 60'                                                                                     
bash -c 'mkdir -p $ghusername && cd $ghusername && git hub mirror $ghusername/*'
```

Using that and cron, it clones all repos of all people I follow every 3 hours or so.
This was done out of frustration during one of the github downtimes.

**Comment by dfm** [comment]
Haha! That is _awesome_. My goal is slightly different but this is a great idea.
